"""add ride_type to ride

Revision ID: 4aad5a6874c2
Revises: fa961b46270f
Create Date: 2026-06-22 10:40:16.706771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aad5a6874c2'
down_revision = 'fa961b46270f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ride_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.drop_column('ride_type')

    # ### end Alembic commands ###
