"""add monthly goal

Revision ID: fa961b46270f
Revises: 1716b8fb343b
Create Date: 2026-06-20 11:04:47.757425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa961b46270f'
down_revision = '1716b8fb343b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_goal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('monthly_goal')

    # ### end Alembic commands ###
